### ISSUE TITLE
Error metric CloudWatch

### ISSUE THREAD

**Issue by emileswarts** [ministryofjustice/network-access-control-infrastructure#185]
### User Story

As a network administrator
I expect to see metrics for all errors regardless of casing in Grafana
So that issues don't go undetected.

### Value / Purpose

Currently we only match on "Error:" to create metrics in Grafana.
Improve monitoring by matching on ERROR, error and Error.

### Useful Contacts

emile@madetech.com

### Additional Information

In the root main.tf file in this repo, we set up all the strings to match on for metrics.
Add ERROR and error to the metrics so they can be picked up.
Add this to Grafana as well, and set alarms on these to send notifications to Slack.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green
- [ ] Grafana is displaying metrics for all errors
- [ ] Alerts for all errors are sent to Slack

**Comment by Gary-H9** [comment]
https://github.com/ministryofjustice/network-access-control-infrastructure/commit/2b238f88101bd74473d5e3f724d8825275d139bf  - has added the strings to the main repository.

**Comment by Gary-H9** [comment]
This ticket was completed circa two weeks ago, apologies for not updating it sooner. When a log filter is created in Prometheus, everything is downcased, as a result "Error" "error" and "ERROR" were all being subsumed into the same metric. As such we had to create the log filters in the below fashion in main.tf

"  log_filters = [
    "Sent Access-Accept",
    "Sent Access-Reject",
    "Ignoring request to auth proto tcp address",
    "Ignoring request to auth address",
    "Error: post_auth - Failed to find attribute",
    "Error: python",
    "Shared secret is incorrect",
    "unknown CA",
    "authorized_macs: users: Matched entry",
    "Health Check: OK",
    "Failed to start task",
    "?'error' ?'Error' ?'ERROR'"
  ]"

This encapsulates all error scenarios.

**Comment by Gary-H9** [comment]
This ticket was completed circa two weeks ago, apologies for not updating it sooner. When a log filter is created in Prometheus, everything is downcased, as a result "Error" "error" and "ERROR" were all being subsumed into the same metric. As such we had to create the log filters in the below fashion in main.tf

"  log_filters = [
    "Sent Access-Accept",
    "Sent Access-Reject",
    "Ignoring request to auth proto tcp address",
    "Ignoring request to auth address",
    "Error: post_auth - Failed to find attribute",
    "Error: python",
    "Shared secret is incorrect",
    "unknown CA",
    "authorized_macs: users: Matched entry",
    "Health Check: OK",
    "Failed to start task",
    "?'error' ?'Error' ?'ERROR'"
  ]"

This encapsulates all error scenarios.
