### ISSUE TITLE
Create multi-AZ diagram

### ISSUE THREAD

**Issue by emileswarts** [ministryofjustice/network-access-control-infrastructure#198]
### User Story

As a network administrator
I want to understand how NACS multi AZ is configured
So that I can make decisions based on this and share information with key stakeholders

### Value / Purpose

Documentation to understand NACS

### Useful Contacts

emile@madetech.com

### Definition of Done

Diagram committed to github, and rendered in the documentation

**Comment by Gary-H9** [comment]
Complete [here](https://github.com/ministryofjustice/network-access-control-infrastructure/commit/28b2601028225881ab1a9843c6893565d0b15159).
