### ISSUE TITLE
Update Owner tag on this repo

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/network-access-control-infrastructure#247]
### User Story

 "owner"            = "nac@digital.justice.gov.uk"
We do not have access to this email address 
This need to be replaced by lanwifi-devops@digital.justice.gov.uk

### Value / Purpose

Ensure that codebase reflect correct address for the team.

### Definition of Done

- [ ] Tag updated with correct value 
- [ ] README has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by NNavickas1** [comment]
https://dsdmoj.atlassian.net/jira/software/c/projects/ND/boards/1430/backlog?epics=visible&selectedIssue=ND-85&text=owner
